from pathlib import Path

import pytest

from sdai.agent_platform.native import NativeSyncError, sync_native_agents
from sdai.scaffold import init_project
from sdai.v05_scaffold import install_v05_scaffold


def _project(tmp_path: Path) -> None:
    init_project(tmp_path)
    install_v05_scaffold(tmp_path)


def test_sync_generates_provider_native_agents_and_claude_skill_mirror(tmp_path: Path):
    _project(tmp_path)
    changed = sync_native_agents(tmp_path, provider="all")
    assert changed

    assert (tmp_path / ".codex" / "agents" / "architect.toml").exists()
    assert (tmp_path / ".github" / "agents" / "architect.agent.md").exists()
    assert (tmp_path / ".claude" / "agents" / "architect.md").exists()
    assert (tmp_path / ".gemini" / "agents" / "architect.md").exists()

    codex = (tmp_path / ".codex" / "agents" / "developer.toml").read_text(encoding="utf-8")
    assert 'name = "developer"' in codex
    assert 'sandbox_mode = "workspace-write"' in codex

    claude = (tmp_path / ".claude" / "agents" / "architect.md").read_text(encoding="utf-8")
    assert "permissionMode: plan" in claude
    assert "architecture-design" in claude

    assert (tmp_path / ".claude" / "skills" / "architecture-design" / "SKILL.md").exists()
    assert (tmp_path / ".agents" / "skills" / "architecture-design" / "SKILL.md").exists()


def test_sync_does_not_duplicate_shared_skills_for_providers_that_use_agents_skills(tmp_path: Path):
    _project(tmp_path)
    sync_native_agents(tmp_path, provider="codex")
    sync_native_agents(tmp_path, provider="copilot")
    sync_native_agents(tmp_path, provider="gemini")

    assert not (tmp_path / ".codex" / "skills").exists()
    assert not (tmp_path / ".github" / "skills").exists()
    assert not (tmp_path / ".gemini" / "skills").exists()


def test_sync_protects_unmanaged_native_agent_files(tmp_path: Path):
    _project(tmp_path)
    target = tmp_path / ".github" / "agents" / "architect.agent.md"
    target.parent.mkdir(parents=True)
    target.write_text("# hand-authored custom agent\n", encoding="utf-8")

    with pytest.raises(NativeSyncError):
        sync_native_agents(tmp_path, provider="copilot")

    sync_native_agents(tmp_path, provider="copilot", force=True)
    assert "Generated by SD-AI" in target.read_text(encoding="utf-8")
